FROM node:16.13.2
ARG GITHUB_TOKEN=${GITHUB_TOKEN}
ARG VALIDATOR_BRANCH=${JAVA_VALIDATOR_BRANCH}

RUN apt-get update

RUN apt-get install -y git

WORKDIR /app

RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

RUN git clone --branch ${VALIDATOR_BRANCH} https://github.com/KA226-COVID/java-evaluator.git

WORKDIR /app/java-evaluator/server

RUN npm ci

EXPOSE ${JAVA_EVALUATOR_PORT}

ENTRYPOINT [ "npm", "run", "prod" ]
