FROM openjdk:8-jdk

WORKDIR /app

COPY ./src_volume/questions-storage/ /app/questions-storage/

WORKDIR /app/questions-storage

RUN chmod +x mvnw
# Fix EOL from windows
RUN sed -i 's/\r$//' mvnw

EXPOSE 8080

ENTRYPOINT [ "./mvnw" , "spring-boot:run", "-Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005\""]
