FROM openjdk:8-jdk
ARG REPO_BRANCH=${REPO_BRANCH}

RUN apt-get update

RUN apt-get install -y git

WORKDIR /app

RUN git clone --branch ${REPO_BRANCH} https://github.com/JuezLTI/questions-storage.git

WORKDIR /app/questions-storage

RUN chmod +x mvnw

EXPOSE 8080

ENTRYPOINT [ "./mvnw", "spring-boot:run" ]
