# Webpack state
# -------------------------------------------------------------------------

FROM node:16.13.2 AS node-build

COPY ./src_volume/codetest /app/codetest

WORKDIR /app/codetest

# Bundled assets are at /app/codetest/public/build
RUN npm ci && npm run build


# Tsugi stage
# -------------------------------------------------------------------------

FROM php:7.3.21-apache AS php-setup

# PHP extensions
RUN apt-get update && apt-get install -y git netcat libzip-dev zip sendmail && apt-get clean -y
RUN docker-php-ext-install pdo pdo_mysql mysqli zip
RUN a2enmod rewrite
# PHP Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./src_volume/tsugi/                       /var/www/html/tsugi/
COPY ./src_volume/codetest/                    /var/www/html/tsugi/mod/codetest/
COPY ./src_volume/codetest/init-tsugi.sh       /var/www/html/tsugi/admin/init-tsugi.sh

WORKDIR /var/www/html/tsugi/mod/codetest

RUN composer install && composer update

RUN mkdir tmp && chmod 777 tmp && cd /tmp && mkdir codetest && chmod 777 codetest

WORKDIR /var/www/html/tsugi/mod

RUN chmod 777 codetest

WORKDIR /var/www/html/tsugi/admin

# Fix EOL from windows
RUN sed -i 's/\r$//' init-tsugi.sh

EXPOSE 80

COPY --from=node-build /app/codetest/public/ /var/www/html/tsugi/mod/codetest/public/

ENTRYPOINT ["/bin/bash", "init-tsugi.sh"]
