FROM openjdk:11-jdk
ARG JAVA_VALIDATOR_BRANCH=${JAVA_VALIDATOR_BRANCH}
ARG NODE_VERSION=${NODE_VERSION}

RUN apt-get update && apt-get install -y git curl

ENV NVM_DIR=/root/.nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

RUN npm install -g nodemon

WORKDIR /app
RUN mkdir -p java-evaluator/server/public/zip

# RUN git clone --branch ${JAVA_VALIDATOR_BRANCH} https://github.com/JuezLTI/java-evaluator.git

COPY ./src_volume/java-evaluator/server/package.json /app/java-evaluator/server/package.json
COPY ./src_volume/java-evaluator/server/package-lock.json /app/java-evaluator/server/package-lock.json

WORKDIR /app/java-evaluator/server

RUN npm ci

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "watch:dev" ]
