FROM node:16.13.2

WORKDIR /app

COPY ./src_volume/feedback-manager/ /app/feedback-manager/

WORKDIR /app/feedback-manager/minimal feedback

RUN npm i

EXPOSE 3003

ENTRYPOINT [ "npm", "run", "prod" ]
