FROM node:16.13.2
ARG FEEDBACK_MANAGER_BRANCH=${FEEDBACK_MANAGER_BRANCH}

RUN apt-get update

RUN apt-get install -y git

WORKDIR /app

RUN git clone --branch ${FEEDBACK_MANAGER_BRANCH} https://github.com/JuezLTI/feedback-manager.git

WORKDIR "/app/feedback-manager"

RUN npm i

EXPOSE 3003

ENTRYPOINT [ "npm", "run", "prod" ]
