FROM node:16.13.2

RUN npm install -g nodemon

WORKDIR /app
RUN mkdir -p sql-evaluator/server/public/zip

# RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

# RUN git clone --branch ${SQL_VALIDATOR_BRANCH} https://github.com/JuezLTI/sql-evaluator.git

COPY ./src_volume/sql-evaluator/server/package.json /app/sql-evaluator/server/package.json
COPY ./src_volume/sql-evaluator/server/package-lock.json /app/sql-evaluator/server/package-lock.json

WORKDIR /app/sql-evaluator/server

RUN npm ci
# RUN npm install

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "watch:dev" ]
