FROM node:16.13.2

RUN npm install -g nodemon

WORKDIR /app
RUN mkdir -p java-evaluator/server/public/zip

# RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

# RUN git clone --branch ${JAVA_VALIDATOR_BRANCH} https://github.com/KA226-COVID/java-evaluator.git

COPY ./src_volume/java-evaluator/server/package.json /app/java-evaluator/server/package.json
COPY ./src_volume/java-evaluator/server/package-lock.json /app/java-evaluator/server/package-lock.json

WORKDIR /app/java-evaluator/server

RUN npm ci

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "watch:dev" ]
