FROM node:16.13.2
ARG XML_VALIDATOR_BRANCH=${XML_VALIDATOR_BRANCH}

RUN apt-get update

RUN apt-get install -y git

WORKDIR /app

RUN git clone --branch ${XML_VALIDATOR_BRANCH} https://github.com/JuezLTI/xml-evaluator.git

WORKDIR /app/xml-evaluator/server

RUN npm ci

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "prod" ]
