FROM node:16.13.2
ARG SQL_VALIDATOR_BRANCH=${SQL_VALIDATOR_BRANCH}

RUN npm install -g nodemon

WORKDIR /app

RUN git clone --branch ${SQL_VALIDATOR_BRANCH} https://github.com/JuezLTI/sql-evaluator.git

RUN mkdir -p /app/sql-evaluator/server/public/zip

WORKDIR /app/sql-evaluator/server

RUN npm ci
# RUN npm install

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "prod" ]
